const test=require('node:test');const assert=require('node:assert/strict');
const {splitForSpeech,ordered,toPlainText}=require('../web/text.js');
test('Chinese sentence boundaries',()=>assert.deepEqual(splitForSpeech('你好。咱们慢慢说！'),['你好。','咱们慢慢说！']));
test('bounded chunks and no punctuation-only calls',()=>{const result=splitForSpeech('字'.repeat(151));assert.deepEqual(result.map(x=>x.length),[60,60,31]);assert.deepEqual(splitForSpeech(' ！？；\n'),[]);});
test('Unicode codepoints are not broken',()=>{const result=splitForSpeech('字😀'.repeat(40),60);assert.equal(Array.from(result[0]).length,60);});
test('final captions ordered by recording and segment',()=>{let records=new Map([[1,{run:2,id:1,text:'三'}],[2,{run:1,id:5,text:'一'}],[3,{run:2,id:0,text:'二'}]]);assert.equal(toPlainText(records),'一\n二\n三');});
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function worklet(){const messages=[];let Processor;class Base{constructor(){this.port={postMessage:m=>messages.push(m)}}}const context={AudioWorkletProcessor:Base,registerProcessor:(n,c)=>{assert.equal(n,'pcm-capture');Processor=c;},Float32Array,ArrayBuffer,DataView,Math};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../web/pcm-worklet.js'),'utf8'),context);return {processor:new Processor(),messages};}
test('actual PCM worklet source: flush tail, little-endian and silence output',()=>{const {processor,messages}=worklet();let input=new Float32Array(2177).fill(.5),output=new Float32Array(2177).fill(1);processor.process([[input]],[[output]]);assert.equal(messages.length,1);assert.equal(messages[0].buffer.byteLength,4096);assert.equal(new DataView(messages[0].buffer).getInt16(0,true),16384);assert.ok(output.every(x=>x===0));processor.port.onmessage({data:'flush'});assert.equal(messages[1].buffer.byteLength,129*2);assert.equal(messages[2].type,'flushed');processor.process([[input]],[[output]]);assert.equal(messages.length,3);});
test('actual PCM worklet source: stereo downmix and clipping',()=>{const {processor,messages}=worklet();processor.process([[new Float32Array([2,-2,1]),new Float32Array([2,-2,-1])]],[[new Float32Array(3)]]);processor.port.onmessage({data:'flush'});const data=new DataView(messages[0].buffer);assert.equal(data.getInt16(0,true),32767);assert.equal(data.getInt16(2,true),-32768);assert.equal(data.getInt16(4,true),0);});
